/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableSubmitRouteImport } from './routes/timetable-submit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentConnectRouteImport } from './routes/student.connect'
import { Route as StudentAiConnectRouteImport } from './routes/student.ai-connect'
import { Route as LecturerUploadRouteImport } from './routes/lecturer.upload'

const TimetableSubmitRoute = TimetableSubmitRouteImport.update({
  id: '/timetable-submit',
  path: '/timetable-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentConnectRoute = StudentConnectRouteImport.update({
  id: '/student/connect',
  path: '/student/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAiConnectRoute = StudentAiConnectRouteImport.update({
  id: '/student/ai-connect',
  path: '/student/ai-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerUploadRoute = LecturerUploadRouteImport.update({
  id: '/lecturer/upload',
  path: '/lecturer/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/timetable-submit': typeof TimetableSubmitRoute
  '/lecturer/upload': typeof LecturerUploadRoute
  '/student/ai-connect': typeof StudentAiConnectRoute
  '/student/connect': typeof StudentConnectRoute
  '/student/login': typeof StudentLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/timetable-submit': typeof TimetableSubmitRoute
  '/lecturer/upload': typeof LecturerUploadRoute
  '/student/ai-connect': typeof StudentAiConnectRoute
  '/student/connect': typeof StudentConnectRoute
  '/student/login': typeof StudentLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/timetable-submit': typeof TimetableSubmitRoute
  '/lecturer/upload': typeof LecturerUploadRoute
  '/student/ai-connect': typeof StudentAiConnectRoute
  '/student/connect': typeof StudentConnectRoute
  '/student/login': typeof StudentLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/timetable-submit'
    | '/lecturer/upload'
    | '/student/ai-connect'
    | '/student/connect'
    | '/student/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/timetable-submit'
    | '/lecturer/upload'
    | '/student/ai-connect'
    | '/student/connect'
    | '/student/login'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/timetable-submit'
    | '/lecturer/upload'
    | '/student/ai-connect'
    | '/student/connect'
    | '/student/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  TimetableSubmitRoute: typeof TimetableSubmitRoute
  LecturerUploadRoute: typeof LecturerUploadRoute
  StudentAiConnectRoute: typeof StudentAiConnectRoute
  StudentConnectRoute: typeof StudentConnectRoute
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable-submit': {
      id: '/timetable-submit'
      path: '/timetable-submit'
      fullPath: '/timetable-submit'
      preLoaderRoute: typeof TimetableSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/connect': {
      id: '/student/connect'
      path: '/student/connect'
      fullPath: '/student/connect'
      preLoaderRoute: typeof StudentConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/ai-connect': {
      id: '/student/ai-connect'
      path: '/student/ai-connect'
      fullPath: '/student/ai-connect'
      preLoaderRoute: typeof StudentAiConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/upload': {
      id: '/lecturer/upload'
      path: '/lecturer/upload'
      fullPath: '/lecturer/upload'
      preLoaderRoute: typeof LecturerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  TimetableSubmitRoute: TimetableSubmitRoute,
  LecturerUploadRoute: LecturerUploadRoute,
  StudentAiConnectRoute: StudentAiConnectRoute,
  StudentConnectRoute: StudentConnectRoute,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
