/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversityFormsSubmitRouteImport } from './routes/university-forms-submit'
import { Route as TimetableSubmitRouteImport } from './routes/timetable-submit'
import { Route as StudyMaterialsSubmitRouteImport } from './routes/study-materials-submit'
import { Route as OnlineClassSubmitRouteImport } from './routes/online-class-submit'
import { Route as LecturerContactsSubmitRouteImport } from './routes/lecturer-contacts-submit'
import { Route as ExamSubmitRouteImport } from './routes/exam-submit'
import { Route as EventsNotesSubmitRouteImport } from './routes/events-notes-submit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssignmentSubmitRouteImport } from './routes/assignment-submit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentLoginRouteImport } from './routes/student.login'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentConnectRouteImport } from './routes/student.connect'
import { Route as StudentAiConnectRouteImport } from './routes/student.ai-connect'
import { Route as LecturerTimetableRouteImport } from './routes/lecturer.timetable'
import { Route as LecturerStudyMaterialsRouteImport } from './routes/lecturer.study-materials'
import { Route as LecturerOnlineClassesRouteImport } from './routes/lecturer.online-classes'
import { Route as LecturerLecturerContactsRouteImport } from './routes/lecturer.lecturer-contacts'
import { Route as LecturerExamScheduleRouteImport } from './routes/lecturer.exam-schedule'
import { Route as LecturerDashboardRouteImport } from './routes/lecturer.dashboard'
import { Route as LecturerAssignmentsRouteImport } from './routes/lecturer.assignments'

const UniversityFormsSubmitRoute = UniversityFormsSubmitRouteImport.update({
  id: '/university-forms-submit',
  path: '/university-forms-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableSubmitRoute = TimetableSubmitRouteImport.update({
  id: '/timetable-submit',
  path: '/timetable-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyMaterialsSubmitRoute = StudyMaterialsSubmitRouteImport.update({
  id: '/study-materials-submit',
  path: '/study-materials-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineClassSubmitRoute = OnlineClassSubmitRouteImport.update({
  id: '/online-class-submit',
  path: '/online-class-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerContactsSubmitRoute = LecturerContactsSubmitRouteImport.update({
  id: '/lecturer-contacts-submit',
  path: '/lecturer-contacts-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSubmitRoute = ExamSubmitRouteImport.update({
  id: '/exam-submit',
  path: '/exam-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNotesSubmitRoute = EventsNotesSubmitRouteImport.update({
  id: '/events-notes-submit',
  path: '/events-notes-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentSubmitRoute = AssignmentSubmitRouteImport.update({
  id: '/assignment-submit',
  path: '/assignment-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentConnectRoute = StudentConnectRouteImport.update({
  id: '/student/connect',
  path: '/student/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAiConnectRoute = StudentAiConnectRouteImport.update({
  id: '/student/ai-connect',
  path: '/student/ai-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerTimetableRoute = LecturerTimetableRouteImport.update({
  id: '/lecturer/timetable',
  path: '/lecturer/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerStudyMaterialsRoute = LecturerStudyMaterialsRouteImport.update({
  id: '/lecturer/study-materials',
  path: '/lecturer/study-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerOnlineClassesRoute = LecturerOnlineClassesRouteImport.update({
  id: '/lecturer/online-classes',
  path: '/lecturer/online-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerLecturerContactsRoute =
  LecturerLecturerContactsRouteImport.update({
    id: '/lecturer/lecturer-contacts',
    path: '/lecturer/lecturer-contacts',
    getParentRoute: () => rootRouteImport,
  } as any)
const LecturerExamScheduleRoute = LecturerExamScheduleRouteImport.update({
  id: '/lecturer/exam-schedule',
  path: '/lecturer/exam-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerDashboardRoute = LecturerDashboardRouteImport.update({
  id: '/lecturer/dashboard',
  path: '/lecturer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturerAssignmentsRoute = LecturerAssignmentsRouteImport.update({
  id: '/lecturer/assignments',
  path: '/lecturer/assignments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignment-submit': typeof AssignmentSubmitRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/events-notes-submit': typeof EventsNotesSubmitRoute
  '/exam-submit': typeof ExamSubmitRoute
  '/lecturer-contacts-submit': typeof LecturerContactsSubmitRoute
  '/online-class-submit': typeof OnlineClassSubmitRoute
  '/study-materials-submit': typeof StudyMaterialsSubmitRoute
  '/timetable-submit': typeof TimetableSubmitRoute
  '/university-forms-submit': typeof UniversityFormsSubmitRoute
  '/lecturer/assignments': typeof LecturerAssignmentsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/exam-schedule': typeof LecturerExamScheduleRoute
  '/lecturer/lecturer-contacts': typeof LecturerLecturerContactsRoute
  '/lecturer/online-classes': typeof LecturerOnlineClassesRoute
  '/lecturer/study-materials': typeof LecturerStudyMaterialsRoute
  '/lecturer/timetable': typeof LecturerTimetableRoute
  '/student/ai-connect': typeof StudentAiConnectRoute
  '/student/connect': typeof StudentConnectRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignment-submit': typeof AssignmentSubmitRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/events-notes-submit': typeof EventsNotesSubmitRoute
  '/exam-submit': typeof ExamSubmitRoute
  '/lecturer-contacts-submit': typeof LecturerContactsSubmitRoute
  '/online-class-submit': typeof OnlineClassSubmitRoute
  '/study-materials-submit': typeof StudyMaterialsSubmitRoute
  '/timetable-submit': typeof TimetableSubmitRoute
  '/university-forms-submit': typeof UniversityFormsSubmitRoute
  '/lecturer/assignments': typeof LecturerAssignmentsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/exam-schedule': typeof LecturerExamScheduleRoute
  '/lecturer/lecturer-contacts': typeof LecturerLecturerContactsRoute
  '/lecturer/online-classes': typeof LecturerOnlineClassesRoute
  '/lecturer/study-materials': typeof LecturerStudyMaterialsRoute
  '/lecturer/timetable': typeof LecturerTimetableRoute
  '/student/ai-connect': typeof StudentAiConnectRoute
  '/student/connect': typeof StudentConnectRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignment-submit': typeof AssignmentSubmitRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/events-notes-submit': typeof EventsNotesSubmitRoute
  '/exam-submit': typeof ExamSubmitRoute
  '/lecturer-contacts-submit': typeof LecturerContactsSubmitRoute
  '/online-class-submit': typeof OnlineClassSubmitRoute
  '/study-materials-submit': typeof StudyMaterialsSubmitRoute
  '/timetable-submit': typeof TimetableSubmitRoute
  '/university-forms-submit': typeof UniversityFormsSubmitRoute
  '/lecturer/assignments': typeof LecturerAssignmentsRoute
  '/lecturer/dashboard': typeof LecturerDashboardRoute
  '/lecturer/exam-schedule': typeof LecturerExamScheduleRoute
  '/lecturer/lecturer-contacts': typeof LecturerLecturerContactsRoute
  '/lecturer/online-classes': typeof LecturerOnlineClassesRoute
  '/lecturer/study-materials': typeof LecturerStudyMaterialsRoute
  '/lecturer/timetable': typeof LecturerTimetableRoute
  '/student/ai-connect': typeof StudentAiConnectRoute
  '/student/connect': typeof StudentConnectRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/login': typeof StudentLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignment-submit'
    | '/auth'
    | '/dashboard'
    | '/events-notes-submit'
    | '/exam-submit'
    | '/lecturer-contacts-submit'
    | '/online-class-submit'
    | '/study-materials-submit'
    | '/timetable-submit'
    | '/university-forms-submit'
    | '/lecturer/assignments'
    | '/lecturer/dashboard'
    | '/lecturer/exam-schedule'
    | '/lecturer/lecturer-contacts'
    | '/lecturer/online-classes'
    | '/lecturer/study-materials'
    | '/lecturer/timetable'
    | '/student/ai-connect'
    | '/student/connect'
    | '/student/dashboard'
    | '/student/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignment-submit'
    | '/auth'
    | '/dashboard'
    | '/events-notes-submit'
    | '/exam-submit'
    | '/lecturer-contacts-submit'
    | '/online-class-submit'
    | '/study-materials-submit'
    | '/timetable-submit'
    | '/university-forms-submit'
    | '/lecturer/assignments'
    | '/lecturer/dashboard'
    | '/lecturer/exam-schedule'
    | '/lecturer/lecturer-contacts'
    | '/lecturer/online-classes'
    | '/lecturer/study-materials'
    | '/lecturer/timetable'
    | '/student/ai-connect'
    | '/student/connect'
    | '/student/dashboard'
    | '/student/login'
  id:
    | '__root__'
    | '/'
    | '/assignment-submit'
    | '/auth'
    | '/dashboard'
    | '/events-notes-submit'
    | '/exam-submit'
    | '/lecturer-contacts-submit'
    | '/online-class-submit'
    | '/study-materials-submit'
    | '/timetable-submit'
    | '/university-forms-submit'
    | '/lecturer/assignments'
    | '/lecturer/dashboard'
    | '/lecturer/exam-schedule'
    | '/lecturer/lecturer-contacts'
    | '/lecturer/online-classes'
    | '/lecturer/study-materials'
    | '/lecturer/timetable'
    | '/student/ai-connect'
    | '/student/connect'
    | '/student/dashboard'
    | '/student/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentSubmitRoute: typeof AssignmentSubmitRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EventsNotesSubmitRoute: typeof EventsNotesSubmitRoute
  ExamSubmitRoute: typeof ExamSubmitRoute
  LecturerContactsSubmitRoute: typeof LecturerContactsSubmitRoute
  OnlineClassSubmitRoute: typeof OnlineClassSubmitRoute
  StudyMaterialsSubmitRoute: typeof StudyMaterialsSubmitRoute
  TimetableSubmitRoute: typeof TimetableSubmitRoute
  UniversityFormsSubmitRoute: typeof UniversityFormsSubmitRoute
  LecturerAssignmentsRoute: typeof LecturerAssignmentsRoute
  LecturerDashboardRoute: typeof LecturerDashboardRoute
  LecturerExamScheduleRoute: typeof LecturerExamScheduleRoute
  LecturerLecturerContactsRoute: typeof LecturerLecturerContactsRoute
  LecturerOnlineClassesRoute: typeof LecturerOnlineClassesRoute
  LecturerStudyMaterialsRoute: typeof LecturerStudyMaterialsRoute
  LecturerTimetableRoute: typeof LecturerTimetableRoute
  StudentAiConnectRoute: typeof StudentAiConnectRoute
  StudentConnectRoute: typeof StudentConnectRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLoginRoute: typeof StudentLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/university-forms-submit': {
      id: '/university-forms-submit'
      path: '/university-forms-submit'
      fullPath: '/university-forms-submit'
      preLoaderRoute: typeof UniversityFormsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable-submit': {
      id: '/timetable-submit'
      path: '/timetable-submit'
      fullPath: '/timetable-submit'
      preLoaderRoute: typeof TimetableSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-materials-submit': {
      id: '/study-materials-submit'
      path: '/study-materials-submit'
      fullPath: '/study-materials-submit'
      preLoaderRoute: typeof StudyMaterialsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-class-submit': {
      id: '/online-class-submit'
      path: '/online-class-submit'
      fullPath: '/online-class-submit'
      preLoaderRoute: typeof OnlineClassSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer-contacts-submit': {
      id: '/lecturer-contacts-submit'
      path: '/lecturer-contacts-submit'
      fullPath: '/lecturer-contacts-submit'
      preLoaderRoute: typeof LecturerContactsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-submit': {
      id: '/exam-submit'
      path: '/exam-submit'
      fullPath: '/exam-submit'
      preLoaderRoute: typeof ExamSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events-notes-submit': {
      id: '/events-notes-submit'
      path: '/events-notes-submit'
      fullPath: '/events-notes-submit'
      preLoaderRoute: typeof EventsNotesSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment-submit': {
      id: '/assignment-submit'
      path: '/assignment-submit'
      fullPath: '/assignment-submit'
      preLoaderRoute: typeof AssignmentSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/connect': {
      id: '/student/connect'
      path: '/student/connect'
      fullPath: '/student/connect'
      preLoaderRoute: typeof StudentConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/ai-connect': {
      id: '/student/ai-connect'
      path: '/student/ai-connect'
      fullPath: '/student/ai-connect'
      preLoaderRoute: typeof StudentAiConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/timetable': {
      id: '/lecturer/timetable'
      path: '/lecturer/timetable'
      fullPath: '/lecturer/timetable'
      preLoaderRoute: typeof LecturerTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/study-materials': {
      id: '/lecturer/study-materials'
      path: '/lecturer/study-materials'
      fullPath: '/lecturer/study-materials'
      preLoaderRoute: typeof LecturerStudyMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/online-classes': {
      id: '/lecturer/online-classes'
      path: '/lecturer/online-classes'
      fullPath: '/lecturer/online-classes'
      preLoaderRoute: typeof LecturerOnlineClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/lecturer-contacts': {
      id: '/lecturer/lecturer-contacts'
      path: '/lecturer/lecturer-contacts'
      fullPath: '/lecturer/lecturer-contacts'
      preLoaderRoute: typeof LecturerLecturerContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/exam-schedule': {
      id: '/lecturer/exam-schedule'
      path: '/lecturer/exam-schedule'
      fullPath: '/lecturer/exam-schedule'
      preLoaderRoute: typeof LecturerExamScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/dashboard': {
      id: '/lecturer/dashboard'
      path: '/lecturer/dashboard'
      fullPath: '/lecturer/dashboard'
      preLoaderRoute: typeof LecturerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecturer/assignments': {
      id: '/lecturer/assignments'
      path: '/lecturer/assignments'
      fullPath: '/lecturer/assignments'
      preLoaderRoute: typeof LecturerAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentSubmitRoute: AssignmentSubmitRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EventsNotesSubmitRoute: EventsNotesSubmitRoute,
  ExamSubmitRoute: ExamSubmitRoute,
  LecturerContactsSubmitRoute: LecturerContactsSubmitRoute,
  OnlineClassSubmitRoute: OnlineClassSubmitRoute,
  StudyMaterialsSubmitRoute: StudyMaterialsSubmitRoute,
  TimetableSubmitRoute: TimetableSubmitRoute,
  UniversityFormsSubmitRoute: UniversityFormsSubmitRoute,
  LecturerAssignmentsRoute: LecturerAssignmentsRoute,
  LecturerDashboardRoute: LecturerDashboardRoute,
  LecturerExamScheduleRoute: LecturerExamScheduleRoute,
  LecturerLecturerContactsRoute: LecturerLecturerContactsRoute,
  LecturerOnlineClassesRoute: LecturerOnlineClassesRoute,
  LecturerStudyMaterialsRoute: LecturerStudyMaterialsRoute,
  LecturerTimetableRoute: LecturerTimetableRoute,
  StudentAiConnectRoute: StudentAiConnectRoute,
  StudentConnectRoute: StudentConnectRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLoginRoute: StudentLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
